
# OpenSfM will use the default parameters from opensfm/config.py
# Set here any parameter that you want to override for this dataset
# For example:
feature_type: SIFT_GPU
matcher_type: SIFT_GPU

# It has to be "1" for at least the extracting and possibly matching images part, in SIFT_GPU.
# It is better to run the reconstruction in "4"
#processes: 1                  # Number of threads to use
processes: 4                  # Number of threads to use
depthmap_min_consistent_views: 3      # Min number of views that should reconstruct a point for it to be valid
depthmap_save_debug_files: no         # Save debug files with partial reconstruction results
feature_process_size: 4096
#feature_process_size: 3072
bundle_use_gcp: yes
feature_use_adaptive_suppression: yes
use_altitude_tag: no

# NEED_TO_TEST:

# Params for track creation
#min_track_length: 3             # Minimum number of features/images per track
#triangulation_type: FULL                # Triangulation type : either considering all rays (FULL), or sing a RANSAC variant (ROBUST)
#five_point_algo_min_inliers: 20         # Minimum number of inliers for considering a two view reconstruction valid
#robust_matching_min_match: 20           # Minimum number of matches to accept matches between two images
