
# OpenSfM will use the default parameters from opensfm/config.py
# Set here any parameter that you want to override for this dataset
# For example:
feature_type: AKAZE
processes: 4                  # Number of threads to use
depthmap_min_consistent_views: 3      # Min number of views that should reconstruct a point for it to be valid
depthmap_save_debug_files: no         # Save debug files with partial reconstruction results
feature_process_size: 3072
bundle_use_gcp: yes
feature_use_adaptive_suppression: yes
use_altitude_tag: yes
